version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(swe)"

  - package-ecosystem: terraform
    directories:
      - /infra/bootstrap
      - /infra/envs/dev
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(swe)"
